### ISSUE TITLE
Proactive mode bug

### ISSUE THREAD

**Issue by bocon13** [brandonheller/riplpox#1]
When the following is run:
~/pox/pox.py riplpox.riplpox --topo=ft,4 --routing=st --mode=proactive

We get the following error:
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/ubuntu/pox/pox/lib/revent/revent.py", line 234, in raiseEventNoErrors
    return self.raiseEvent(event, _args, *_kw)
  File "/home/ubuntu/pox/pox/lib/revent/revent.py", line 281, in raiseEvent
    rv = event._invoke(handler, _args, *_kw)
  File "/home/ubuntu/pox/pox/lib/revent/revent.py", line 159, in _invoke
    return handler(self, _args, *_kw)
  File "/home/ubuntu/riplpox/riplpox/riplpox.py", line 274, in _handle_ConnectionUp
    self._install_proactive_flows()
  File "/home/ubuntu/riplpox/riplpox/riplpox.py", line 249, in _install_proactive_flows
    self._install_proactive_path(src, dst)
  File "/home/ubuntu/riplpox/riplpox/riplpox.py", line 149, in _install_proactive_path
    hash_ = self._src_dst_hash(src_dpid, dst_dpid)
NameError: global name 'src_dpid' is not defined

In line 149 of riplpox.py:
hash_ = self._src_dst_hash(src_dpid, dst_dpid)
src_dpid and dst_dpid are not defined

**Comment by brandonheller** [comment]
Fixed in 040c9f6.  Thanks bocon!  Was a sloppy code change I forgot to test.  Speaking of which, RipL could really use a basic testing suite.

**Comment by bocon13** [comment]
no problem! thanks!
